// <auto-generated />
using System;
using AspireApp1.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspireApp1.Server.Migrations
{
    [DbContext(typeof(AspireDbContext))]
    partial class AspireDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspireApp1.Server.Models.faWiersz", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("fakturaId")
                        .HasColumnType("int");

                    b.Property<decimal?>("kursWaluty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("nrWiersza")
                        .HasColumnType("int");

                    b.Property<decimal?>("p_11")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("p_12")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("p_7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("p_8A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("p_8B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("p_9A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("podmiotid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("fakturaId");

                    b.HasIndex("podmiotid");

                    b.ToTable("FakturaWiersze");
                });

            modelBuilder.Entity("AspireApp1.Server.Models.faktura", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("kodWaluty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("p_1")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("p_13_1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("p_14W")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("p_14_1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("p_15")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("p_2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("p_6Do")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("p_6Od")
                        .HasColumnType("datetime2");

                    b.Property<int>("podmiot1Id")
                        .HasColumnType("int");

                    b.Property<int>("podmiot2Id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("podmiot1Id");

                    b.HasIndex("podmiot2Id");

                    b.ToTable("faktura", (string)null);
                });

            modelBuilder.Entity("AspireApp1.Server.Models.podmiot", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("kodWaluty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("p_1")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("p_13_1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("p_14W")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("p_14_1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("p_15")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("p_2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("p_6Do")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("p_6Od")
                        .HasColumnType("datetime2");

                    b.Property<int?>("podmiot1Id")
                        .HasColumnType("int");

                    b.Property<int?>("podmiot2Id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("podmiot1Id");

                    b.HasIndex("podmiot2Id");

                    b.ToTable("Podmioty");
                });

            modelBuilder.Entity("AspireApp1.Server.Models.faWiersz", b =>
                {
                    b.HasOne("AspireApp1.Server.Models.faktura", "faktura")
                        .WithMany("wiersze")
                        .HasForeignKey("fakturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspireApp1.Server.Models.podmiot", null)
                        .WithMany("wiersze")
                        .HasForeignKey("podmiotid");

                    b.Navigation("faktura");
                });

            modelBuilder.Entity("AspireApp1.Server.Models.faktura", b =>
                {
                    b.HasOne("AspireApp1.Server.Models.podmiot", "podmiot1")
                        .WithMany()
                        .HasForeignKey("podmiot1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AspireApp1.Server.Models.podmiot", "podmiot2")
                        .WithMany()
                        .HasForeignKey("podmiot2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("podmiot1");

                    b.Navigation("podmiot2");
                });

            modelBuilder.Entity("AspireApp1.Server.Models.podmiot", b =>
                {
                    b.HasOne("AspireApp1.Server.Models.podmiot", "podmiot1")
                        .WithMany()
                        .HasForeignKey("podmiot1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AspireApp1.Server.Models.podmiot", "podmiot2")
                        .WithMany()
                        .HasForeignKey("podmiot2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("podmiot1");

                    b.Navigation("podmiot2");
                });

            modelBuilder.Entity("AspireApp1.Server.Models.faktura", b =>
                {
                    b.Navigation("wiersze");
                });

            modelBuilder.Entity("AspireApp1.Server.Models.podmiot", b =>
                {
                    b.Navigation("wiersze");
                });
#pragma warning restore 612, 618
        }
    }
}
