// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using leaderboardServer.Data;

#nullable disable

namespace leaderboardServer.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20260420074159_fix")]
    partial class fix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("leaderboardServer.Models.Score", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("gameMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isSuspicious")
                        .HasColumnType("bit");

                    b.Property<int>("score")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("time")
                        .HasColumnType("time");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Scores", "dbo");
                });

            modelBuilder.Entity("leaderboardServer.Models.Top10", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("scoreId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("scoreId");

                    b.ToTable("Top10", "dbo");
                });

            modelBuilder.Entity("leaderboardServer.Models.Top10snapshots", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Top10snapshots", "dbo");
                });

            modelBuilder.Entity("leaderboardServer.Models.snapshotEntries", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Top10snapshotsId")
                        .HasColumnType("int");

                    b.Property<string>("gameMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isSuspicious")
                        .HasColumnType("bit");

                    b.Property<int>("score")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("time")
                        .HasColumnType("time");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Top10snapshotsId");

                    b.ToTable("snapshotEntries", "dbo");
                });

            modelBuilder.Entity("leaderboardServer.Models.Top10", b =>
                {
                    b.HasOne("leaderboardServer.Models.Score", null)
                        .WithMany()
                        .HasForeignKey("scoreId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("leaderboardServer.Models.snapshotEntries", b =>
                {
                    b.HasOne("leaderboardServer.Models.Top10snapshots", "Top10snapshots")
                        .WithMany("Entries")
                        .HasForeignKey("Top10snapshotsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Top10snapshots");
                });

            modelBuilder.Entity("leaderboardServer.Models.Top10snapshots", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
