// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using leaderboardServer.Data;

#nullable disable

namespace leaderboardServer.Migrations
{
    [DbContext(typeof(dbContext))]
    partial class dbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("leaderboardServer.Models.Score", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("gameMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isSuspicious")
                        .HasColumnType("bit");

                    b.Property<int>("score")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("time")
                        .HasColumnType("time");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("score");

                    b.HasIndex("time");

                    b.ToTable("Scores", "dbo");
                });

            modelBuilder.Entity("leaderboardServer.Models.Top10", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("rank")
                        .HasColumnType("int");

                    b.Property<int?>("scoreId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("rank")
                        .IsUnique()
                        .HasFilter("[rank] IS NOT NULL");

                    b.HasIndex("scoreId");

                    b.ToTable("Top10", "dbo");
                });

            modelBuilder.Entity("leaderboardServer.Models.Top10snapshot", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("date");

                    b.ToTable("Top10snapshots", "dbo");
                });

            modelBuilder.Entity("leaderboardServer.Models.snapshotEntry", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Top10snapshotId")
                        .HasColumnType("int");

                    b.Property<string>("gameMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isSuspicious")
                        .HasColumnType("bit");

                    b.Property<int>("rank")
                        .HasColumnType("int");

                    b.Property<int>("score")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("time")
                        .HasColumnType("time");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Top10snapshotId", "rank")
                        .IsUnique();

                    b.ToTable("snapshotEntries", "dbo");
                });

            modelBuilder.Entity("leaderboardServer.Models.Top10", b =>
                {
                    b.HasOne("leaderboardServer.Models.Score", "Score")
                        .WithMany()
                        .HasForeignKey("scoreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Score");
                });

            modelBuilder.Entity("leaderboardServer.Models.snapshotEntry", b =>
                {
                    b.HasOne("leaderboardServer.Models.Top10snapshot", "Top10snapshot")
                        .WithMany("Entries")
                        .HasForeignKey("Top10snapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Top10snapshot");
                });

            modelBuilder.Entity("leaderboardServer.Models.Top10snapshot", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
