// <auto-generated />
using System;
using KSeF_app_fix.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KSeF_app_fix.Server.Migrations
{
    [DbContext(typeof(KsefContext))]
    [Migration("20260409085103_InitSync")]
    partial class InitSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ksef")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KSeF_app_fix.Server.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GLN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Address", "ksef");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsBankOwnAccount")
                        .HasColumnType("int");

                    b.Property<string>("Swift")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BankAccount", "ksef");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.Carrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Carrier", "ksef");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.Charge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SettlementId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId");

                    b.ToTable("Charges", "ksef");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactInfo", "ksef");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ContractDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContractNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TermsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TermsId")
                        .IsUnique();

                    b.ToTable("Contract", "ksef");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.Deduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SettlementId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId");

                    b.ToTable("Deductions", "ksef");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CurrencyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FactorBankAccountId")
                        .HasColumnType("int");

                    b.Property<string>("FooterNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssuePlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KsefNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SellerBankAccountId")
                        .HasColumnType("int");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("FactorBankAccountId");

                    b.HasIndex("SellerBankAccountId");

                    b.HasIndex("SellerId");

                    b.ToTable("Invoice", "ksef");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.InvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerPiceNetto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PricePerPieceNetto");

                    b.Property<string>("PriceTotalNetto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TaxRate")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceLine", "ksef");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.OrderInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TermsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TermsId")
                        .IsUnique();

                    b.ToTable("OrderInfo", "ksef");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.PartialPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentInfoId");

                    b.ToTable("PartialPayment", "ksef");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.Party", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContactInfoId")
                        .HasColumnType("int");

                    b.Property<int?>("CorrespondenceAddressID")
                        .HasColumnType("int");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eori")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<int?>("MainAddressId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContactInfoId");

                    b.HasIndex("CorrespondenceAddressID");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("MainAddressId");

                    b.ToTable("Party", "ksef");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.PaymentInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPartial")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTermsDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId")
                        .IsUnique();

                    b.ToTable("PaymentInfo", "ksef");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.Settlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalToPay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId")
                        .IsUnique();

                    b.ToTable("Settlement", "ksef");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.TaxSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Brutto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("Netto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PLNAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TaxRate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("TaxSummary", "ksef");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.Terms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeliveryTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId")
                        .IsUnique();

                    b.ToTable("Terms", "ksef");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.TransportInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CargoDescription")
                        .HasColumnType("int");

                    b.Property<int?>("CarrierId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PackagingUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShipFromId")
                        .HasColumnType("int");

                    b.Property<int?>("ShipToID")
                        .HasColumnType("int");

                    b.Property<int?>("ShipViaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TermsId")
                        .HasColumnType("int");

                    b.Property<string>("TransportOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransportType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("ShipFromId");

                    b.HasIndex("ShipToID");

                    b.HasIndex("ShipViaID");

                    b.HasIndex("TermsId")
                        .IsUnique();

                    b.ToTable("TransportInfo", "ksef");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.Carrier", b =>
                {
                    b.HasOne("KSeF_app_fix.Server.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.Charge", b =>
                {
                    b.HasOne("KSeF_app_fix.Server.Models.Settlement", "Settlement")
                        .WithMany("Charges")
                        .HasForeignKey("SettlementId");

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.Contract", b =>
                {
                    b.HasOne("KSeF_app_fix.Server.Models.Terms", null)
                        .WithOne("Contract")
                        .HasForeignKey("KSeF_app_fix.Server.Models.Contract", "TermsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.Deduction", b =>
                {
                    b.HasOne("KSeF_app_fix.Server.Models.Settlement", "Settlement")
                        .WithMany("Deductions")
                        .HasForeignKey("SettlementId");

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.Invoice", b =>
                {
                    b.HasOne("KSeF_app_fix.Server.Models.Party", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KSeF_app_fix.Server.Models.BankAccount", "FactorBankAccount")
                        .WithMany()
                        .HasForeignKey("FactorBankAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KSeF_app_fix.Server.Models.BankAccount", "SellerBankAccount")
                        .WithMany()
                        .HasForeignKey("SellerBankAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KSeF_app_fix.Server.Models.Party", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("FactorBankAccount");

                    b.Navigation("Seller");

                    b.Navigation("SellerBankAccount");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.InvoiceLine", b =>
                {
                    b.HasOne("KSeF_app_fix.Server.Models.Invoice", null)
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.OrderInfo", b =>
                {
                    b.HasOne("KSeF_app_fix.Server.Models.Terms", null)
                        .WithOne("Order")
                        .HasForeignKey("KSeF_app_fix.Server.Models.OrderInfo", "TermsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.PartialPayment", b =>
                {
                    b.HasOne("KSeF_app_fix.Server.Models.PaymentInfo", "PaymentInfo")
                        .WithMany("PartialPayments")
                        .HasForeignKey("PaymentInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentInfo");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.Party", b =>
                {
                    b.HasOne("KSeF_app_fix.Server.Models.ContactInfo", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactInfoId");

                    b.HasOne("KSeF_app_fix.Server.Models.Address", "CorrespondenceAddress")
                        .WithMany()
                        .HasForeignKey("CorrespondenceAddressID");

                    b.HasOne("KSeF_app_fix.Server.Models.Invoice", null)
                        .WithMany("OtherParties")
                        .HasForeignKey("InvoiceId");

                    b.HasOne("KSeF_app_fix.Server.Models.Address", "MainAddress")
                        .WithMany()
                        .HasForeignKey("MainAddressId");

                    b.Navigation("Contact");

                    b.Navigation("CorrespondenceAddress");

                    b.Navigation("MainAddress");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.PaymentInfo", b =>
                {
                    b.HasOne("KSeF_app_fix.Server.Models.Invoice", null)
                        .WithOne("Payment")
                        .HasForeignKey("KSeF_app_fix.Server.Models.PaymentInfo", "InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.Settlement", b =>
                {
                    b.HasOne("KSeF_app_fix.Server.Models.Invoice", null)
                        .WithOne("Settlement")
                        .HasForeignKey("KSeF_app_fix.Server.Models.Settlement", "InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.TaxSummary", b =>
                {
                    b.HasOne("KSeF_app_fix.Server.Models.Invoice", null)
                        .WithMany("TaxSummaries")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.Terms", b =>
                {
                    b.HasOne("KSeF_app_fix.Server.Models.Invoice", null)
                        .WithOne("TransactionTerms")
                        .HasForeignKey("KSeF_app_fix.Server.Models.Terms", "InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.TransportInfo", b =>
                {
                    b.HasOne("KSeF_app_fix.Server.Models.Carrier", "Carrier")
                        .WithMany()
                        .HasForeignKey("CarrierId");

                    b.HasOne("KSeF_app_fix.Server.Models.Address", "ShipFrom")
                        .WithMany()
                        .HasForeignKey("ShipFromId");

                    b.HasOne("KSeF_app_fix.Server.Models.Address", "ShipTo")
                        .WithMany()
                        .HasForeignKey("ShipToID");

                    b.HasOne("KSeF_app_fix.Server.Models.Address", "ShipVia")
                        .WithMany()
                        .HasForeignKey("ShipViaID");

                    b.HasOne("KSeF_app_fix.Server.Models.Terms", null)
                        .WithOne("Transport")
                        .HasForeignKey("KSeF_app_fix.Server.Models.TransportInfo", "TermsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrier");

                    b.Navigation("ShipFrom");

                    b.Navigation("ShipTo");

                    b.Navigation("ShipVia");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.Invoice", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("OtherParties");

                    b.Navigation("Payment");

                    b.Navigation("Settlement");

                    b.Navigation("TaxSummaries");

                    b.Navigation("TransactionTerms");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.PaymentInfo", b =>
                {
                    b.Navigation("PartialPayments");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.Settlement", b =>
                {
                    b.Navigation("Charges");

                    b.Navigation("Deductions");
                });

            modelBuilder.Entity("KSeF_app_fix.Server.Models.Terms", b =>
                {
                    b.Navigation("Contract");

                    b.Navigation("Order");

                    b.Navigation("Transport");
                });
#pragma warning restore 612, 618
        }
    }
}
